development:
  adapter: postgresql
  encoding: unicode
  database: Restaurant_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: Restaurant_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: Restaurant_production
  pool: 5
